### ISSUE TITLE
✨ Challenge solution

### ISSUE THREAD

**Issue by kevin-schmitt** [reedsy/challenges#36]
Good morning

Thank you for this deposit.

Are there solutions available to the challenges?
For example with
- good practices (testing, architecture)
- performances

Otherwise, possible to create a subdirectory with the solution for each challenge?

THANKS

**Comment by pdfrod** [comment]
Hello!

Sorry, but we don't plan on making solutions available. We use these challenges as part of our recruitment process, therefore it would defeat their purpose if we made the solutions publicly available.
